// ─────────────────────────────────────────────────────────────────────────────
// LaundryMate POS — Seed Data
// Realistic demo data for development & testing
// ─────────────────────────────────────────────────────────────────────────────

import type {
  Service,
  Addon,
  Customer,
  Order,
  Expense,
  ShopSettings,
} from '../types';

// ─── Helpers ──────────────────────────────────────────────────────────────────

const daysAgo  = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString();
const hoursAgo = (n: number) => new Date(Date.now() - n * 3_600_000).toISOString();
const minsAgo  = (n: number) => new Date(Date.now() - n * 60_000).toISOString();
const inHours  = (n: number) => new Date(Date.now() + n * 3_600_000).toISOString();
const now      = ()           => new Date().toISOString();

// ─── Services ─────────────────────────────────────────────────────────────────

export const SEED_SERVICES: Service[] = [
  {
    id: 'svc-001',
    name: 'Wash & Fold',
    category: 'basic',
    unit: 'kg',
    price: 60,
    duration: '2–3 days',
    description: 'Machine wash with tumble dry and neatly folded.',
    isActive: true,
    createdAt: daysAgo(60),
  },
  {
    id: 'svc-002',
    name: 'Dry Cleaning',
    category: 'premium',
    unit: 'pc',
    price: 180,
    duration: '3–5 days',
    description: 'Professional dry cleaning for delicate garments.',
    isActive: true,
    createdAt: daysAgo(60),
  },
  {
    id: 'svc-003',
    name: 'Press / Iron',
    category: 'basic',
    unit: 'pc',
    price: 25,
    duration: '1 day',
    description: 'Steam pressing and ironing per piece.',
    isActive: true,
    createdAt: daysAgo(60),
  },
  {
    id: 'svc-004',
    name: 'Wash & Iron',
    category: 'standard',
    unit: 'kg',
    price: 90,
    duration: '2–3 days',
    description: 'Full wash, dry, and iron combo service.',
    isActive: true,
    createdAt: daysAgo(60),
  },
  {
    id: 'svc-005',
    name: 'Express Service',
    category: 'express',
    unit: 'kg',
    price: 120,
    duration: 'Same day',
    description: 'Rush same-day washing and drying.',
    isActive: true,
    createdAt: daysAgo(60),
  },
  {
    id: 'svc-006',
    name: 'Bedsheet & Linen',
    category: 'standard',
    unit: 'pc',
    price: 150,
    duration: '2 days',
    description: 'Bedsheets, pillowcases, and table linens.',
    isActive: true,
    createdAt: daysAgo(60),
  },
  {
    id: 'svc-007',
    name: 'Comforter / Duvet',
    category: 'bulky',
    unit: 'pc',
    price: 350,
    duration: '3–4 days',
    description: 'Thick comforters, duvets, and heavy blankets.',
    isActive: true,
    createdAt: daysAgo(60),
  },
  {
    id: 'svc-008',
    name: 'Sneaker Cleaning',
    category: 'specialty',
    unit: 'pair',
    price: 250,
    duration: '2–3 days',
    description: 'Deep clean for all types of sneakers.',
    isActive: true,
    createdAt: daysAgo(60),
  },
  {
    id: 'svc-009',
    name: 'Curtain Wash',
    category: 'bulky',
    unit: 'pc',
    price: 200,
    duration: '3 days',
    description: 'Curtains, drapes, and window coverings.',
    isActive: true,
    createdAt: daysAgo(60),
  },
  {
    id: 'svc-010',
    name: 'Uniform Package',
    category: 'standard',
    unit: 'set',
    price: 110,
    duration: '2 days',
    description: 'Wash, iron, and fold for uniforms per set.',
    isActive: true,
    createdAt: daysAgo(60),
  },
];

// ─── Add-ons ──────────────────────────────────────────────────────────────────

export const SEED_ADDONS: Addon[] = [
  {
    id: 'adn-001',
    name: 'Fabric Softener',
    price: 20,
    description: 'Adds softness and a fresh scent to your laundry.',
    isActive: true,
  },
  {
    id: 'adn-002',
    name: 'Bleach Treatment',
    price: 35,
    description: 'Whitening bleach treatment for whites.',
    isActive: true,
  },
  {
    id: 'adn-003',
    name: 'Stain Removal',
    price: 50,
    description: 'Pre-treatment for tough stains before washing.',
    isActive: true,
  },
  {
    id: 'adn-004',
    name: 'Odor Eliminator',
    price: 30,
    description: 'Neutralizes strong odors from clothes.',
    isActive: true,
  },
  {
    id: 'adn-005',
    name: 'Detergent Upgrade',
    price: 25,
    description: 'Premium hypoallergenic detergent upgrade.',
    isActive: true,
  },
  {
    id: 'adn-006',
    name: 'Folding / Packaging',
    price: 15,
    description: 'Neatly folded and individually packaged in a bag.',
    isActive: true,
  },
];

// ─── Customers ────────────────────────────────────────────────────────────────

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: 'cus-001',
    name: 'Maria Santos',
    phone: '09171234567',
    email: 'maria.santos@email.com',
    address: '123 Mabini St, Brgy. Central, Quezon City',
    loyaltyPoints: 84,
    totalOrders: 12,
    totalSpent: 8400,
    joinDate: daysAgo(180),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(5),
  },
  {
    id: 'cus-002',
    name: 'Juan dela Cruz',
    phone: '09281234567',
    email: 'juan.delacruz@email.com',
    address: '456 Rizal Ave, Brgy. Poblacion, Pasig City',
    loyaltyPoints: 56,
    totalOrders: 8,
    totalSpent: 5600,
    joinDate: daysAgo(120),
    createdAt: daysAgo(120),
    updatedAt: daysAgo(10),
  },
  {
    id: 'cus-003',
    name: 'Ana Reyes',
    phone: '09391234567',
    email: 'ana.reyes@email.com',
    address: '789 Luna St, Brgy. San Lorenzo, Makati City',
    loyaltyPoints: 170,
    totalOrders: 20,
    totalSpent: 17000,
    joinDate: daysAgo(365),
    createdAt: daysAgo(365),
    updatedAt: daysAgo(2),
  },
  {
    id: 'cus-004',
    name: 'Pedro Bautista',
    phone: '09451234567',
    email: null,
    address: null,
    loyaltyPoints: 18,
    totalOrders: 3,
    totalSpent: 1800,
    joinDate: daysAgo(45),
    createdAt: daysAgo(45),
    updatedAt: daysAgo(20),
  },
  {
    id: 'cus-005',
    name: 'Rosa Mendoza',
    phone: '09561234567',
    email: 'rosa.mendoza@email.com',
    address: '321 Bonifacio St, Mandaluyong City',
    loyaltyPoints: 126,
    totalOrders: 15,
    totalSpent: 12600,
    joinDate: daysAgo(200),
    createdAt: daysAgo(200),
    updatedAt: daysAgo(1),
  },
  {
    id: 'cus-006',
    name: 'Carlo Fernandez',
    phone: '09671234567',
    email: 'carlo.f@email.com',
    address: '654 Aguinaldo Blvd, Taguig City',
    loyaltyPoints: 42,
    totalOrders: 6,
    totalSpent: 4200,
    joinDate: daysAgo(90),
    createdAt: daysAgo(90),
    updatedAt: daysAgo(7),
  },
  {
    id: 'cus-007',
    name: 'Liza Gomez',
    phone: '09781234567',
    email: 'liza.gomez@email.com',
    address: '987 Magsaysay Ave, San Juan City',
    loyaltyPoints: 35,
    totalOrders: 5,
    totalSpent: 3500,
    joinDate: daysAgo(75),
    createdAt: daysAgo(75),
    updatedAt: daysAgo(3),
  },
  {
    id: 'cus-008',
    name: 'Dante Villanueva',
    phone: '09891234567',
    email: null,
    address: '111 Quezon Blvd, Quezon City',
    loyaltyPoints: 10,
    totalOrders: 2,
    totalSpent: 1000,
    joinDate: daysAgo(30),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(15),
  },
];

// ─── Orders ───────────────────────────────────────────────────────────────────

export const SEED_ORDERS: Order[] = [
  // ORD-001 — Completed, cash, walk-in
  {
    id: 'ORD-001',
    customerId: 'cus-001',
    customerName: 'Maria Santos',
    customerPhone: '09171234567',
    items: [
      {
        id: 'itm-001a',
        orderId: 'ORD-001',
        serviceId: 'svc-001',
        serviceName: 'Wash & Fold',
        qty: 4,
        unit: 'kg',
        pricePerUnit: 60,
        subtotal: 240,
        addons: [
          { addonId: 'adn-001', addonName: 'Fabric Softener', price: 20 },
          { addonId: 'adn-003', addonName: 'Stain Removal',   price: 50 },
        ],
      },
      {
        id: 'itm-001b',
        orderId: 'ORD-001',
        serviceId: 'svc-003',
        serviceName: 'Press / Iron',
        qty: 6,
        unit: 'pc',
        pricePerUnit: 25,
        subtotal: 150,
        addons: [],
      },
    ],
    servicesSubtotal: 390,
    addonsSubtotal: 70,
    deliveryFee: 0,
    discount: 0,
    total: 460,
    amountPaid: 500,
    change: 40,
    paymentMethod: 'cash',
    status: 'completed',
    isPickup: false,
    pickupAddress: null,
    deliveryAddress: null,
    scheduledAt: null,
    driverName: null,
    deliveryStatus: null,
    notes: 'Handle whites with care. Separate from colored.',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
    readyAt: daysAgo(3),
    claimedAt: daysAgo(2),
  },

  // ORD-002 — Ready, GCash, pickup & delivery
  {
    id: 'ORD-002',
    customerId: 'cus-003',
    customerName: 'Ana Reyes',
    customerPhone: '09391234567',
    items: [
      {
        id: 'itm-002a',
        orderId: 'ORD-002',
        serviceId: 'svc-002',
        serviceName: 'Dry Cleaning',
        qty: 3,
        unit: 'pc',
        pricePerUnit: 180,
        subtotal: 540,
        addons: [
          { addonId: 'adn-002', addonName: 'Bleach Treatment', price: 35 },
        ],
      },
      {
        id: 'itm-002b',
        orderId: 'ORD-002',
        serviceId: 'svc-006',
        serviceName: 'Bedsheet & Linen',
        qty: 2,
        unit: 'pc',
        pricePerUnit: 150,
        subtotal: 300,
        addons: [
          { addonId: 'adn-004', addonName: 'Odor Eliminator', price: 30 },
        ],
      },
    ],
    servicesSubtotal: 840,
    addonsSubtotal: 65,
    deliveryFee: 80,
    discount: 50,
    total: 935,
    amountPaid: 935,
    change: 0,
    paymentMethod: 'gcash',
    status: 'ready',
    isPickup: true,
    pickupAddress: '789 Luna St, Makati City',
    deliveryAddress: '789 Luna St, Makati City',
    scheduledAt: inHours(3),
    driverName: 'Carlo Reyes',
    deliveryStatus: 'out_for_delivery',
    notes: 'Call before delivery.',
    createdAt: daysAgo(4),
    updatedAt: hoursAgo(2),
    readyAt: hoursAgo(2),
    claimedAt: null,
  },

  // ORD-003 — Processing, unpaid, express
  {
    id: 'ORD-003',
    customerId: 'cus-002',
    customerName: 'Juan dela Cruz',
    customerPhone: '09281234567',
    items: [
      {
        id: 'itm-003a',
        orderId: 'ORD-003',
        serviceId: 'svc-005',
        serviceName: 'Express Service',
        qty: 3,
        unit: 'kg',
        pricePerUnit: 120,
        subtotal: 360,
        addons: [
          { addonId: 'adn-004', addonName: 'Odor Eliminator',  price: 30 },
          { addonId: 'adn-005', addonName: 'Detergent Upgrade', price: 25 },
        ],
      },
    ],
    servicesSubtotal: 360,
    addonsSubtotal: 55,
    deliveryFee: 0,
    discount: 0,
    total: 415,
    amountPaid: 0,
    change: 0,
    paymentMethod: null,
    status: 'processing',
    isPickup: false,
    pickupAddress: null,
    deliveryAddress: null,
    scheduledAt: null,
    driverName: null,
    deliveryStatus: null,
    notes: 'URGENT — needs by 5:00 PM today.',
    createdAt: hoursAgo(4),
    updatedAt: hoursAgo(3),
    readyAt: null,
    claimedAt: null,
  },

  // ORD-004 — Pending, pickup, unpaid
  {
    id: 'ORD-004',
    customerId: 'cus-005',
    customerName: 'Rosa Mendoza',
    customerPhone: '09561234567',
    items: [
      {
        id: 'itm-004a',
        orderId: 'ORD-004',
        serviceId: 'svc-004',
        serviceName: 'Wash & Iron',
        qty: 5,
        unit: 'kg',
        pricePerUnit: 90,
        subtotal: 450,
        addons: [
          { addonId: 'adn-006', addonName: 'Folding / Packaging', price: 15 },
        ],
      },
      {
        id: 'itm-004b',
        orderId: 'ORD-004',
        serviceId: 'svc-006',
        serviceName: 'Bedsheet & Linen',
        qty: 3,
        unit: 'pc',
        pricePerUnit: 150,
        subtotal: 450,
        addons: [
          { addonId: 'adn-001', addonName: 'Fabric Softener', price: 20 },
        ],
      },
    ],
    servicesSubtotal: 900,
    addonsSubtotal: 35,
    deliveryFee: 100,
    discount: 0,
    total: 1035,
    amountPaid: 0,
    change: 0,
    paymentMethod: null,
    status: 'pending',
    isPickup: true,
    pickupAddress: '321 Bonifacio St, Mandaluyong City',
    deliveryAddress: '321 Bonifacio St, Mandaluyong City',
    scheduledAt: inHours(6),
    driverName: '',
    deliveryStatus: 'pending',
    notes: '',
    createdAt: minsAgo(45),
    updatedAt: minsAgo(45),
    readyAt: null,
    claimedAt: null,
  },

  // ORD-005 — Completed, Maya, comforter specialty
  {
    id: 'ORD-005',
    customerId: 'cus-006',
    customerName: 'Carlo Fernandez',
    customerPhone: '09671234567',
    items: [
      {
        id: 'itm-005a',
        orderId: 'ORD-005',
        serviceId: 'svc-007',
        serviceName: 'Comforter / Duvet',
        qty: 2,
        unit: 'pc',
        pricePerUnit: 350,
        subtotal: 700,
        addons: [
          { addonId: 'adn-004', addonName: 'Odor Eliminator', price: 30 },
        ],
      },
    ],
    servicesSubtotal: 700,
    addonsSubtotal: 30,
    deliveryFee: 0,
    discount: 0,
    total: 730,
    amountPaid: 730,
    change: 0,
    paymentMethod: 'maya',
    status: 'completed',
    isPickup: false,
    pickupAddress: null,
    deliveryAddress: null,
    scheduledAt: null,
    driverName: null,
    deliveryStatus: null,
    notes: '',
    createdAt: daysAgo(8),
    updatedAt: daysAgo(4),
    readyAt: daysAgo(5),
    claimedAt: daysAgo(4),
  },

  // ORD-006 — Completed, cash, walk-in sneakers
  {
    id: 'ORD-006',
    customerId: 'cus-007',
    customerName: 'Liza Gomez',
    customerPhone: '09781234567',
    items: [
      {
        id: 'itm-006a',
        orderId: 'ORD-006',
        serviceId: 'svc-008',
        serviceName: 'Sneaker Cleaning',
        qty: 2,
        unit: 'pair',
        pricePerUnit: 250,
        subtotal: 500,
        addons: [
          { addonId: 'adn-003', addonName: 'Stain Removal',   price: 50 },
          { addonId: 'adn-006', addonName: 'Folding / Packaging', price: 15 },
        ],
      },
    ],
    servicesSubtotal: 500,
    addonsSubtotal: 65,
    deliveryFee: 0,
    discount: 0,
    total: 565,
    amountPaid: 600,
    change: 35,
    paymentMethod: 'cash',
    status: 'completed',
    isPickup: false,
    pickupAddress: null,
    deliveryAddress: null,
    scheduledAt: null,
    driverName: null,
    deliveryStatus: null,
    notes: 'Jordan Retro 4 — be very careful.',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(7),
    readyAt: daysAgo(8),
    claimedAt: daysAgo(7),
  },

  // ORD-007 — Pending, walk-in, basic
  {
    id: 'ORD-007',
    customerId: null,
    customerName: 'Walk-in Customer',
    customerPhone: null,
    items: [
      {
        id: 'itm-007a',
        orderId: 'ORD-007',
        serviceId: 'svc-001',
        serviceName: 'Wash & Fold',
        qty: 2.5,
        unit: 'kg',
        pricePerUnit: 60,
        subtotal: 150,
        addons: [
          { addonId: 'adn-001', addonName: 'Fabric Softener', price: 20 },
        ],
      },
    ],
    servicesSubtotal: 150,
    addonsSubtotal: 20,
    deliveryFee: 0,
    discount: 0,
    total: 170,
    amountPaid: 0,
    change: 0,
    paymentMethod: null,
    status: 'pending',
    isPickup: false,
    pickupAddress: null,
    deliveryAddress: null,
    scheduledAt: null,
    driverName: null,
    deliveryStatus: null,
    notes: '',
    createdAt: minsAgo(15),
    updatedAt: minsAgo(15),
    readyAt: null,
    claimedAt: null,
  },

  // ORD-008 — Completed, bank transfer, curtains bulk
  {
    id: 'ORD-008',
    customerId: 'cus-004',
    customerName: 'Pedro Bautista',
    customerPhone: '09451234567',
    items: [
      {
        id: 'itm-008a',
        orderId: 'ORD-008',
        serviceId: 'svc-009',
        serviceName: 'Curtain Wash',
        qty: 4,
        unit: 'pc',
        pricePerUnit: 200,
        subtotal: 800,
        addons: [],
      },
    ],
    servicesSubtotal: 800,
    addonsSubtotal: 0,
    deliveryFee: 0,
    discount: 100,
    total: 700,
    amountPaid: 700,
    change: 0,
    paymentMethod: 'bank_transfer',
    status: 'completed',
    isPickup: false,
    pickupAddress: null,
    deliveryAddress: null,
    scheduledAt: null,
    driverName: null,
    deliveryStatus: null,
    notes: 'Discounted — regular customer',
    createdAt: daysAgo(12),
    updatedAt: daysAgo(9),
    readyAt: daysAgo(10),
    claimedAt: daysAgo(9),
  },
];

// ─── Expenses ─────────────────────────────────────────────────────────────────

export const SEED_EXPENSES: Expense[] = [
  {
    id: 'exp-001',
    category: 'rent',
    categoryLabel: 'Rent',
    description: 'Monthly shop rent — March 2026',
    amount: 12000,
    date: daysAgo(9),
    receipt: null,
    createdAt: daysAgo(9),
  },
  {
    id: 'exp-002',
    category: 'salaries',
    categoryLabel: 'Salaries',
    description: 'Staff wages — March 2026 (2 staff)',
    amount: 18000,
    date: daysAgo(8),
    receipt: null,
    createdAt: daysAgo(8),
  },
  {
    id: 'exp-003',
    category: 'utilities',
    categoryLabel: 'Utilities',
    description: 'Electric bill — February 2026',
    amount: 3400,
    date: daysAgo(7),
    receipt: null,
    createdAt: daysAgo(7),
  },
  {
    id: 'exp-004',
    category: 'utilities',
    categoryLabel: 'Utilities',
    description: 'Water bill — February 2026',
    amount: 850,
    date: daysAgo(7),
    receipt: null,
    createdAt: daysAgo(7),
  },
  {
    id: 'exp-005',
    category: 'supplies',
    categoryLabel: 'Supplies',
    description: 'Detergent & fabric softener restock',
    amount: 2200,
    date: daysAgo(5),
    receipt: null,
    createdAt: daysAgo(5),
  },
  {
    id: 'exp-006',
    category: 'supplies',
    categoryLabel: 'Supplies',
    description: 'Plastic bags and packaging materials',
    amount: 650,
    date: daysAgo(4),
    receipt: null,
    createdAt: daysAgo(4),
  },
  {
    id: 'exp-007',
    category: 'maintenance',
    categoryLabel: 'Maintenance',
    description: 'Washing machine drum repair (Unit 2)',
    amount: 2500,
    date: daysAgo(3),
    receipt: null,
    createdAt: daysAgo(3),
  },
  {
    id: 'exp-008',
    category: 'miscellaneous',
    categoryLabel: 'Miscellaneous',
    description: 'Office supplies and receipt paper',
    amount: 320,
    date: daysAgo(2),
    receipt: null,
    createdAt: daysAgo(2),
  },
  {
    id: 'exp-009',
    category: 'maintenance',
    categoryLabel: 'Maintenance',
    description: 'Dryer belt replacement (Unit 1)',
    amount: 800,
    date: daysAgo(1),
    receipt: null,
    createdAt: daysAgo(1),
  },
  {
    id: 'exp-010',
    category: 'supplies',
    categoryLabel: 'Supplies',
    description: 'Bleach and stain remover chemicals',
    amount: 780,
    date: daysAgo(1),
    receipt: null,
    createdAt: daysAgo(1),
  },
];

// ─── Default Shop Settings ────────────────────────────────────────────────────

export const SEED_SETTINGS: ShopSettings = {
  shopName: 'LaundryMate',
  address: '123 Malaya Street, Brgy. Poblacion, Quezon City',
  phone: '(02) 8XXX-XXXX',
  email: 'hello@laundrymate.ph',
  tin: '123-456-789-000',
  currency: '₱',
  loyaltyEnabled: true,
  pickupEnabled: true,
  expressMultiplier: 2,
  receiptFooter: 'Thank you for trusting LaundryMate! 🫧',
};